# Generated by Django 4.1.3 on 2022-11-17 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_article_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='tags',
        ),
        migrations.AddField(
            model_name='tag',
            name='tags',
            field=models.ManyToManyField(related_name='Теги', to='blog.article'),
        ),
    ]
