# Generated by Django 4.1.3 on 2022-11-19 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_rename_tags_tag_tag_article'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='tag_article',
        ),
        migrations.AddField(
            model_name='article',
            name='tag',
            field=models.ManyToManyField(related_name='Теги', to='blog.tag'),
        ),
    ]
