# Generated by Django 4.1.3 on 2023-01-10 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_rename_title_article_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='name',
            new_name='title',
        ),
    ]
