# Generated by Django 4.1.3 on 2023-02-26 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0029_remove_comments_user_comments_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
