# Generated by Django 4.1.3 on 2023-01-03 14:56

from django.db import migrations
import django.utils.timezone
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_product_created_at_alter_product_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(default=django.utils.timezone.now, upload_to='catalog/product/', verbose_name='Картинка'),
            preserve_default=False,
        ),
    ]
