# Generated by Django 4.1.3 on 2023-02-25 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_product_user'),
        ('main', '0002_alter_page_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Назва')),
                ('sort', models.PositiveIntegerField(default=0, verbose_name='Сортування')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активовано')),
                ('product', models.ManyToManyField(to='catalog.product', verbose_name='Продукти')),
            ],
            options={
                'verbose_name': 'Карусель товару',
                'verbose_name_plural': 'Карусель товарів',
                'ordering': ['sort'],
            },
        ),
    ]
