# Generated by Django 4.1.3 on 2023-02-25 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_productset'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productset',
            old_name='product',
            new_name='products',
        ),
    ]
